export const LANGUAGE_CHANGED = "LANGUAGE_CHANGED";
export const USER_LOGGED_IN  = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const TOKEN_CHANGED = "TOKEN_CHANGED";
export const UDID_UPDATED = "UDID_UPDATED";
export const ADDRESS_UPDATED = "ADDRESS_UPDATED";
